# Settings for typos-cli tool
# [Typos Configuration Reference](https://github.com/crate-ci/typos/blob/master/docs/reference.md)
#
# Syntax: .gitignore glob syntax
#        `*`    : match any file in a single level
#        `**`   : recursively match
#        `**/*` : specifies any _files_ at any level (subtly & potentially different)
#
# files -> "identifiers" -> words
# (I *believe* 'identifiers' are some sort of pre-word chunk that will later tbe split into words for checking.)

[default.extend-words]
egui = "egui" # Example for how to ignore a false positive

# [default.extend-ignore-re]  # blank out whole regions; e.g. markdown code fences; see link for syntax

lib_blocking = "lib_blocking"

[files]
extend-exclude = ["**/data/**", "*.log", "*.csv"]
